# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#

title: this is a blog
email: contact@zachn.me
author: Zach

# `>-` means to ignore newlines until next key
description: >-
  A blog for quick thoughts.

# the subpath of your site, e.g. /blog
baseurl: ""
permalink: /:categories/:year/:month/:day/:title/

# the base hostname & protocol for your site, e.g. http://example.com
url: "https://zachn.me"
github_username: ZNielsen
collections_dir: pub
collections:
  stickers:
    output: true
  games:
    output: true
  doors:
    output: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
feed:
  collections:
    - doors
    - games
    - stickers

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
